### ISSUE TITLE
Error in UseMethod("collector_value") :

### ISSUE THREAD

**Issue by junio-AC** [fabiogiglietto/CooRnet_ImgTxt#1]
Hi!
First of all thanks for your work!

I'm trying to use the script for Facebook but while running the first for at line 18

`for (i in 1:length(csv_v)) {
`

 I get this error message

```
Error in UseMethod("collector_value") :                                                                        
  no applicable method for 'collector_value' applied to an object of class "c('collector_skip', 'collector')"
In addition: Warning message:
The following named parsers don't match the column names: platformId, type, date, imageText, account.name, account.handle, postUrl 
```

Since I haven't changed anything I thought it could be due to the export csv options, but I did try a few (with comma or semicolon as "CSV delimiters2 and with comma or without in the "number format") and I still have this error.

Am I missing something? Anyon with the same error?
Thank you so much!

**Comment by fabiogiglietto** [comment]
Hi Junio-AC,
judging from the the error, it seems that the csv was not properly downloaded.

Try

```
library(dplyr)
library(readr)

  df <- readr::read_csv(col_types = cols(
    .default = col_skip(),
    platformId = col_character(),
    type = col_character(),
    date = col_character(),
    imageText = col_character(),
    account.name = col_character(),
    account.handle = col_character(),
    postUrl = col_character()),
    file =  "" # <- copy/paste the link to your CSV here
```
and check that df contains the desired data.

We always used the default export options for delimiter and number format.

Hope it helps. Best, Fabio

**Comment by junio-AC** [comment]
Thank you so much for your fast and kind reply!
Unfortunately still not working.

```
> df <- readr::read_csv(col_types = cols(
+   .default = col_skip(),
+   platformId = col_character(),
+   type = col_character(),
+   date = col_character(),
+   imageText = col_character(),
+   account.name = col_character(),
+   account.handle = col_character(),
+   postUrl = col_character()),
+   file =  "2022-03-08-10-27-19-CET-search-csv-export.csv" # <- copy/paste the link to your CSV here
+   )
Error in UseMethod("collector_value") :                                                                                                                                           
  no applicable method for 'collector_value' applied to an object of class "c('collector_skip', 'collector')"
In addition: Warning message:
The following named parsers don't match the column names: platformId, type, date, imageText, account.name, account.handle, postUrl 
> 
```

I have followed the instructions but I'm wondering if the CSV is right. Should it have all of these columns with these names?

Page Name | User Name | Facebook Id | Page Category | Page Admin Top Country | Page Description | Page Created | Likes at Posting | Followers at Posting | Post Created | Post Created Date | Post Created Time | Type | Total Interactions | Likes | Comments | Shares | Love | Wow | Haha | Sad | Angry | Care | Video Share Status | Is Video Owner? | Post Views | Total Views | Total Views For All Crossposts | Video Length | URL | Message | Link | Final Link | Image Text | Link Text | Description | Sponsor Id | Sponsor Name | Sponsor Category | Total Interactions | Overperforming Score


Thank you again for your time!

**Comment by fabiogiglietto** [comment]
I got it. The issue is with the format of CrowdTangle CSV. I'll adapt the code to make it work on your format.

**Comment by junio-AC** [comment]
Thank you so much, really really appreciated!

**Comment by fabiogiglietto** [comment]
Hi again, do you mind sending over here or by email a sample of your CSV?

**Comment by junio-AC** [comment]
Sure, I'm sending an email!

**Comment by fabiogiglietto** [comment]
I've pushed a version of blueapp.R that supports the old CSV format. You still need a comma separated CSV, I'll add this requirement to the readme page.

Let me know if it works. I wasn't able to fully test with your CSV as the repeated imgText where 0 in the sample file.
